---

- name: If this is a destructive build then asynchronously destroy any nodes that exist.
  destroy_vm:
    vcenter_host: "{{ item.value.vc | default(mgmt_vc) }}"
    vcenter_user: "{{ item.value.username | default(mgmt_vc_username) }}"
    vcenter_password: "{{ item.value.password | default(vc_credentials.amr.password) }}"
    vcenter_port: "{{ item.value.vc_port | default(mgmt_vc_port) }}"
    vm_name: "{{ item.value.name }}"
  with_dict: "{{ vrops_nodes }}"
  register: vrops_destroy
  when: THIS_IS_A_DESTRUCTIVE_BUILD
  no_log: "{{ enable_no_log }}"
  async: 3600
  poll: 0
  tags:
    - vrops_ova_destroy

- name: Wait for and fan in the results from the destroy_vm task.
  async_status:
    jid: "{{ async_result_item.ansible_job_id }}"
  with_items: "{{ vrops_destroy.results }}"
  loop_control:
    loop_var: "async_result_item"
  register: vrops_destroy_results
  when: THIS_IS_A_DESTRUCTIVE_BUILD
  until: vrops_destroy_results.finished
  no_log: "{{ enable_no_log }}"
  delay: 10
  retries: 60
  tags:
    - vrops_ova_destroy
