---

- name: Configure data node ({{ item.value.name }})
  uri:
    url: https://{{ item.value.ip_address }}/casa/node/data
    body: "{{ lookup('template', 'data-config.json') }}"
    method: POST
    user: "{{ default_admin_user }}"
    password: "{{ svc_vrops_admin_password }}"
    force_basic_auth: yes
    headers:
      Content-Type: "application/json;charset=UTF-8"
      Accept: "application/json;charset=UTF-8"
    validate_certs: no
    timeout: 3600
    status_code: 202, 500
  register: data_init_response
  retries: 10
  delay: 10
  until: (data_init_response.status == 202) or (data_init_response.status == 500)
  when: item.value.role == 'data'
  no_log: "{{ enable_no_log }}"
  tags:
    - vrops_data_config

- name: Wait for node ({{ item.value.name }}) to enter cluster
  uri:
    url: https://{{ vrops_nodes.master.ip_address }}/casa/deployment/cluster/current
    user: "{{ default_admin_user }}"
    password: "{{ svc_vrops_admin_password }}"
    force_basic_auth: yes
    headers:
      Content-Type: "application/json"
    validate_certs: no
    status_code: 200
    return_content: yes
  when: item.value.role == 'data'
  register: configuration_status
  until: (item.value.name in configuration_status.content) or (item.value.ip_address in configuration_status.content)
  retries: 60
  delay: 30
  no_log: "{{ enable_no_log }}"
  tags:
    - vrops_data_config

- name: Wait 5 minutes before attempting to add the next data node
  when: item.value.role == 'data'
  pause:
    minutes: 5
  no_log: "{{ enable_no_log }}"
  tags:
    - vrops_data_config
